name: Download New Rain Masks around Berlin
on:
  schedule:
    - cron: "15 * * * *"
#     - cron: "7 */2 * * *"
#     - cron: '0 0-21/3 * * *'
  workflow_dispatch:
  
jobs:
  launch: # my name
    name: Update images with new weather data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Script and Update Images
        run: |
          jupyter nbconvert --to script rainviewer_api.ipynb
          python weather_locations.py
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add weather_locations.csv weather_locations.png
          git commit -m "Updated images on `date` `time` with GitHub Actions"
          git push origin master
